# Generated by Django 3.2.25 on 2024-11-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='patronym',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
