# Generated by Django 3.2.25 on 2024-11-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_designrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequests',
            name='image_sale',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
