# Generated by Django 3.2.25 on 2024-11-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20241113_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequests',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
