# Generated by Django 3.2.25 on 2024-11-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_designrequests_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequests',
            name='category',
        ),
    ]
