# Generated by Django 3.2.25 on 2024-11-13 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_designrequests_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequests',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
