# Generated by Django 3.2.25 on 2024-11-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_designrequests_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequests',
            name='status',
            field=models.CharField(choices=[('N', 'Новая'), ('P', 'Принято в работу'), ('C', 'Выполнено')], default='new', max_length=20),
        ),
    ]
