# Generated by Django 5.1.3 on 2024-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_customuser_comments_alter_designrequests_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='comments',
        ),
        migrations.AddField(
            model_name='designrequests',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
