# Generated by Django 5.1.3 on 2024-11-14 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_customuser_comments_designrequests_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequests',
            name='done_status_image',
            field=models.FileField(blank=True, null=True, upload_to='admin_img/', verbose_name='Обновленное фото дизайна'),
        ),
        migrations.AlterField(
            model_name='designrequests',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='designrequests',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='designrequests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='designrequests',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='designrequests',
            name='image_sale',
            field=models.FileField(blank=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='designrequests',
            name='status',
            field=models.CharField(choices=[('N', 'Новая'), ('P', 'Принято в работу'), ('C', 'Выполнено')], default='N', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='designrequests',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='designrequests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
