# Generated by Django 3.2.25 on 2024-11-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_rename_done_status_image_designrequests_updated_image_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
